services:
    astro:
        build: ./local
        image: php:public
        container_name: astro
        command: ./local/symfony.sh
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_started
            mongodb:
                condition: service_started
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_started
    db:
        image: mysql:8.0
        container_name: astro_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: free_astro
            MYSQL_USER: fen_user
            MYSQL_PASSWORD: fen_password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
    rabbitmq:
        image: rabbitmq:4.2-management
        container_name: astro_rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: astro_user
            RABBITMQ_DEFAULT_PASS: astro_password
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 5s
            retries: 5
    mongodb:
        image: mongo:8.0
        container_name: astro_mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: astro_user
            MONGO_INITDB_ROOT_PASSWORD: astro_password
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
    redis:
        image: redis:8.6
        container_name: astro_redis
        command: redis-server --requirepass astro_password
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
    grafana:
        image: grafana/grafana:latest
        container_name: astro_grafana
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
volumes:
    db_data:
    rabbitmq_data:
    mongodb_data:
    redis_data:
    grafana_data:
