<?php

namespace App\Infra\Adapters\Gateway;

use App\App\Contracts\Gateway\PdfGeneratorInterface;
use App\App\Contracts\Repository\FortuneProviderInterface;
use App\Domain\Entity\Report;
use App\Domain\Entity\User;
use App\Domain\Exceptions\PdfGenerationException;
use Spipu\Html2Pdf\Exception\Html2PdfException;
use Spipu\Html2Pdf\Html2Pdf;

readonly class HtmlToPdfGenerator implements PdfGeneratorInterface
{
    public function __construct(
        private FortuneProviderInterface $fortuneProvider,
        private string $projectDir
    ) {}


    public function generate(User $user, Report $report): string
    {
        try {
            $outputDir = "{$this->projectDir}/public/reports/";
            if (!is_dir($outputDir)) {
                mkdir($outputDir, 0775, true);
            }

            $fileName = "report_{$report->getProcessId()}.pdf";
            $filePath = $outputDir . $fileName;
            $name = htmlspecialchars($user->getName() . ' ' . $user->getFamilyName());
            $sign = htmlspecialchars($user->getZodiac()?->getSign() ?? 'Unknown');
            $period = str_pad($report->getMonth(), 2, '0', STR_PAD_LEFT) . '/' . $report->getYear();
            $fortune = htmlspecialchars($this->fortuneProvider->getRandomFortune());
            $date = new \DateTime()->format('d/m/Y');
            $signEmoji = $this->getSignEmoji($sign);

            $html = <<<HTML
            <page backtop="10mm" backbottom="10mm" backleft="15mm" backright="15mm">
                <style type="text/css">
                    .header { text-align: center; margin-bottom: 10mm; }
                    .title { font-size: 28px; color: #2c1654; font-family: times; }
                    .subtitle { font-size: 13px; color: #7c6f9b; letter-spacing: 2px; }
                    .divider { border-bottom: 2px solid #d4af37; width: 60%; margin: 6mm auto; }
                    .sign-badge {
                        text-align: center; font-size: 40px; margin: 4mm auto;
                    }
                    .sign-name { text-align: center; font-size: 22px; color: #d4af37; font-weight: bold; }
                    .info-table { width: 80%; margin: 6mm auto; font-size: 13px; }
                    .info-table td { padding: 2mm 4mm; }
                    .info-label { color: #7c6f9b; font-weight: bold; text-align: right; width: 35%; }
                    .info-value { color: #2c1654; }
                    .fortune-box {
                        background-color: #f8f4ff;
                        border-left: 4px solid #d4af37;
                        padding: 6mm;
                        margin: 8mm auto;
                        width: 80%;
                        font-size: 14px;
                        color: #3b2d5e;
                        line-height: 1.6;
                        font-style: italic;
                    }
                    .fortune-title { font-size: 16px; color: #2c1654; font-weight: bold; font-style: normal; margin-bottom: 3mm; }
                    .footer { text-align: center; font-size: 10px; color: #aaa; margin-top: 15mm; }
                </style>

                <div class="header">
                    <div class="subtitle">✦ F R E E A S T R O ✦</div>
                    <div class="title">Monthly Horoscope Report</div>
                </div>
                <div class="divider"></div>

                <div class="sign-badge">{$signEmoji}</div>
                <div class="sign-name">{$sign}</div>

                <table class="info-table">
                    <tr><td class="info-label">Name:</td><td class="info-value">{$name}</td></tr>
                    <tr><td class="info-label">Period:</td><td class="info-value">{$period}</td></tr>
                    <tr><td class="info-label">Generated:</td><td class="info-value">{$date}</td></tr>
                </table>

                <div class="fortune-box">
                    <div class="fortune-title">🔮 Your Cosmic Reading</div>
                    {$fortune}
                </div>

                <div class="footer">Generated by FreeAstroAPI — The stars have spoken ✦</div>
            </page>
            HTML;
            $html2pdf = new Html2Pdf();
            $html2pdf->writeHTML($html);
            $html2pdf->output($filePath, 'F');
            return $filePath;
        }  catch (Html2PdfException $exception) {
            throw new PdfGenerationException($exception->getMessage());
        }
    }

    private function getSignEmoji(string $sign): string
    {
        return match ($sign) {
            'Aries' => '♈',
            'Taurus' => '♉',
            'Gemini' => '♊',
            'Cancer' => '♋',
            'Leo' => '♌',
            'Virgo' => '♍',
            'Libra' => '♎',
            'Scorpio' => '♏',
            'Sagittarius' => '♐',
            'Capricorn' => '♑',
            'Aquarius' => '♒',
            'Pisces' => '♓',
            default => '✦',
        };
    }
}
